// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaqrxikqkbfctbekgjiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcXJ4aWtxa2JmY3RiZWtnaml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzYzNjUsImV4cCI6MjA2NTYxMjM2NX0.dAva5flFlrJtZGoTf_4b6o514RPcRYLJLBLuu9mWcFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);